# Generated by Django 4.2.3 on 2023-11-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('revisionNo', models.IntegerField(null=True)),
                ('etag', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLinkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (15, 'Contribution'), (99, 'Rejected'), (100, 'Approved'), (200, 'Published')], db_index=True)),
                ('revisionNo', models.IntegerField(null=True)),
                ('timestamp', models.DateField(db_index=True)),
                ('content', models.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='VoyageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, null=True)),
                ('voyage_id', models.IntegerField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.document')),
                ('link_mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.documentlinkmode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('language_code', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('is_translation', models.BooleanField()),
                ('document_rev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documentrevision')),
            ],
        ),
        migrations.CreateModel(
            name='EnslaverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, null=True)),
                ('enslaver_id', models.IntegerField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.document')),
                ('link_mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.documentlinkmode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnslavedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, null=True)),
                ('enslaved_id', models.IntegerField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.document')),
                ('link_mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.documentlinkmode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
